### ISSUE TITLE
Create slides for final presentation

### ISSUE THREAD

**Issue by Ononymous** [Ononymous/AirNet#24]
Put screenshots, past versions, problems, ideas, and features into a google slide
Design the flow of the presentation

**Comment by Tommygithubaccount123** [comment]
Slides: https://docs.google.com/presentation/d/1cjEfdpIcqsJgkpEPZkCJhc1xu3mLrWevllEf_yh2c14/edit?usp=sharing

**Comment by Tommygithubaccount123** [comment]
Use the rubric from codersSB, literally use their topics for slides

**Comment by Tommygithubaccount123** [comment]
CMD+Shift+4+Space+option

Take screenshot without shadowing

**Comment by Tommygithubaccount123** [comment]
https://www.canva.com/design/DAFhz1USANU/ncoQMHv0Zv2swXnFstyOLQ/edit?utm_content=DAFhz1USANU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
